// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT id, user_id, name, world, vocation, level, sex, residence, guild_name, guild_rank, achievement_points, account_status, last_login, is_main, last_synced_at, created_at, updated_at, deleted_at
FROM characters
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetCharacterByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCharacterByID(ctx context.Context, arg GetCharacterByIDParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByID, arg.ID, arg.UserID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.World,
		&i.Vocation,
		&i.Level,
		&i.Sex,
		&i.Residence,
		&i.GuildName,
		&i.GuildRank,
		&i.AchievementPoints,
		&i.AccountStatus,
		&i.LastLogin,
		&i.IsMain,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCharacter = `-- name: InsertCharacter :one
INSERT INTO characters (
    user_id, name, world, vocation, level, sex,
    residence, guild_name, guild_rank, achievement_points,
    account_status, last_login, is_main, last_synced_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14
)
RETURNING id, user_id, name, world, vocation, level, sex, residence, guild_name, guild_rank, achievement_points, account_status, last_login, is_main, last_synced_at, created_at, updated_at, deleted_at
`

type InsertCharacterParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	Name              string             `json:"name"`
	World             string             `json:"world"`
	Vocation          string             `json:"vocation"`
	Level             int32              `json:"level"`
	Sex               string             `json:"sex"`
	Residence         string             `json:"residence"`
	GuildName         string             `json:"guild_name"`
	GuildRank         string             `json:"guild_rank"`
	AchievementPoints int32              `json:"achievement_points"`
	AccountStatus     string             `json:"account_status"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsMain            bool               `json:"is_main"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) InsertCharacter(ctx context.Context, arg InsertCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, insertCharacter,
		arg.UserID,
		arg.Name,
		arg.World,
		arg.Vocation,
		arg.Level,
		arg.Sex,
		arg.Residence,
		arg.GuildName,
		arg.GuildRank,
		arg.AchievementPoints,
		arg.AccountStatus,
		arg.LastLogin,
		arg.IsMain,
		arg.LastSyncedAt,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.World,
		&i.Vocation,
		&i.Level,
		&i.Sex,
		&i.Residence,
		&i.GuildName,
		&i.GuildRank,
		&i.AchievementPoints,
		&i.AccountStatus,
		&i.LastLogin,
		&i.IsMain,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllActiveCharacters = `-- name: ListAllActiveCharacters :many
SELECT id, user_id, name, world, vocation, level, sex, residence, guild_name, guild_rank, achievement_points, account_status, last_login, is_main, last_synced_at, created_at, updated_at, deleted_at
FROM characters
WHERE deleted_at IS NULL
`

func (q *Queries) ListAllActiveCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listAllActiveCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.World,
			&i.Vocation,
			&i.Level,
			&i.Sex,
			&i.Residence,
			&i.GuildName,
			&i.GuildRank,
			&i.AchievementPoints,
			&i.AccountStatus,
			&i.LastLogin,
			&i.IsMain,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT id, user_id, name, world, vocation, level, sex, residence, guild_name, guild_rank, achievement_points, account_status, last_login, is_main, last_synced_at, created_at, updated_at, deleted_at
FROM characters
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID pgtype.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.World,
			&i.Vocation,
			&i.Level,
			&i.Sex,
			&i.Residence,
			&i.GuildName,
			&i.GuildRank,
			&i.AchievementPoints,
			&i.AccountStatus,
			&i.LastLogin,
			&i.IsMain,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCharacter = `-- name: SoftDeleteCharacter :exec
UPDATE characters
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteCharacterParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteCharacter(ctx context.Context, arg SoftDeleteCharacterParams) error {
	_, err := q.db.Exec(ctx, softDeleteCharacter, arg.ID, arg.UserID)
	return err
}

const updateCharacterSnapshot = `-- name: UpdateCharacterSnapshot :one
UPDATE characters
SET world = $2,
    vocation = $3,
    level = $4,
    sex = $5,
    residence = $6,
    guild_name = $7,
    guild_rank = $8,
    achievement_points = $9,
    account_status = $10,
    last_login = $11,
    is_main = $12,
    last_synced_at = $13
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, name, world, vocation, level, sex, residence, guild_name, guild_rank, achievement_points, account_status, last_login, is_main, last_synced_at, created_at, updated_at, deleted_at
`

type UpdateCharacterSnapshotParams struct {
	ID                pgtype.UUID        `json:"id"`
	World             string             `json:"world"`
	Vocation          string             `json:"vocation"`
	Level             int32              `json:"level"`
	Sex               string             `json:"sex"`
	Residence         string             `json:"residence"`
	GuildName         string             `json:"guild_name"`
	GuildRank         string             `json:"guild_rank"`
	AchievementPoints int32              `json:"achievement_points"`
	AccountStatus     string             `json:"account_status"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsMain            bool               `json:"is_main"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateCharacterSnapshot(ctx context.Context, arg UpdateCharacterSnapshotParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterSnapshot,
		arg.ID,
		arg.World,
		arg.Vocation,
		arg.Level,
		arg.Sex,
		arg.Residence,
		arg.GuildName,
		arg.GuildRank,
		arg.AchievementPoints,
		arg.AccountStatus,
		arg.LastLogin,
		arg.IsMain,
		arg.LastSyncedAt,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.World,
		&i.Vocation,
		&i.Level,
		&i.Sex,
		&i.Residence,
		&i.GuildName,
		&i.GuildRank,
		&i.AchievementPoints,
		&i.AccountStatus,
		&i.LastLogin,
		&i.IsMain,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
