// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: character_snapshots.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCharacterSnapshotsOlderThan = `-- name: DeleteCharacterSnapshotsOlderThan :exec
DELETE FROM character_snapshots
WHERE captured_at < $1
`

func (q *Queries) DeleteCharacterSnapshotsOlderThan(ctx context.Context, capturedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteCharacterSnapshotsOlderThan, capturedAt)
	return err
}

const insertCharacterSnapshot = `-- name: InsertCharacterSnapshot :exec
INSERT INTO character_snapshots (
    character_id, level, vocation, world, achievement_points, captured_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertCharacterSnapshotParams struct {
	CharacterID       pgtype.UUID        `json:"character_id"`
	Level             int32              `json:"level"`
	Vocation          string             `json:"vocation"`
	World             string             `json:"world"`
	AchievementPoints int32              `json:"achievement_points"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) InsertCharacterSnapshot(ctx context.Context, arg InsertCharacterSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertCharacterSnapshot,
		arg.CharacterID,
		arg.Level,
		arg.Vocation,
		arg.World,
		arg.AchievementPoints,
		arg.CapturedAt,
	)
	return err
}

const listCharacterSnapshots = `-- name: ListCharacterSnapshots :many
SELECT id, character_id, level, vocation, world, achievement_points, captured_at
FROM character_snapshots
WHERE character_id = $1
  AND captured_at >= $2
ORDER BY captured_at ASC
`

type ListCharacterSnapshotsParams struct {
	CharacterID pgtype.UUID        `json:"character_id"`
	CapturedAt  pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) ListCharacterSnapshots(ctx context.Context, arg ListCharacterSnapshotsParams) ([]CharacterSnapshot, error) {
	rows, err := q.db.Query(ctx, listCharacterSnapshots, arg.CharacterID, arg.CapturedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterSnapshot
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Level,
			&i.Vocation,
			&i.World,
			&i.AchievementPoints,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
