// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creature_bestiary.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBestiaryByNames = `-- name: GetBestiaryByNames :many
SELECT id, name, difficulty, is_boss, resolved_at, created_at, updated_at, deleted_at
FROM creature_bestiary
WHERE name = ANY($1::text[])
  AND deleted_at IS NULL
`

func (q *Queries) GetBestiaryByNames(ctx context.Context, names []string) ([]CreatureBestiary, error) {
	rows, err := q.db.Query(ctx, getBestiaryByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreatureBestiary
	for rows.Next() {
		var i CreatureBestiary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Difficulty,
			&i.IsBoss,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBestiary = `-- name: UpsertBestiary :exec
INSERT INTO creature_bestiary (name, difficulty, is_boss, resolved_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (name) WHERE deleted_at IS NULL
DO UPDATE SET difficulty = $2, is_boss = $3, resolved_at = now()
`

type UpsertBestiaryParams struct {
	Name       string      `json:"name"`
	Difficulty pgtype.Text `json:"difficulty"`
	IsBoss     bool        `json:"is_boss"`
}

func (q *Queries) UpsertBestiary(ctx context.Context, arg UpsertBestiaryParams) error {
	_, err := q.db.Exec(ctx, upsertBestiary, arg.Name, arg.Difficulty, arg.IsBoss)
	return err
}
