// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_asset_sprites.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpritesByNames = `-- name: GetSpritesByNames :many
SELECT id, kind, name, image_url, resolved_at, created_at, updated_at, deleted_at
FROM game_asset_sprites
WHERE kind = $1
  AND name = ANY($2::text[])
  AND deleted_at IS NULL
`

type GetSpritesByNamesParams struct {
	Kind  string   `json:"kind"`
	Names []string `json:"names"`
}

func (q *Queries) GetSpritesByNames(ctx context.Context, arg GetSpritesByNamesParams) ([]GameAssetSprite, error) {
	rows, err := q.db.Query(ctx, getSpritesByNames, arg.Kind, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameAssetSprite
	for rows.Next() {
		var i GameAssetSprite
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.ImageUrl,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSprite = `-- name: UpsertSprite :exec
INSERT INTO game_asset_sprites (kind, name, image_url, resolved_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (kind, name) WHERE deleted_at IS NULL
DO UPDATE SET image_url = $3, resolved_at = now()
`

type UpsertSpriteParams struct {
	Kind     string      `json:"kind"`
	Name     string      `json:"name"`
	ImageUrl pgtype.Text `json:"image_url"`
}

func (q *Queries) UpsertSprite(ctx context.Context, arg UpsertSpriteParams) error {
	_, err := q.db.Exec(ctx, upsertSprite, arg.Kind, arg.Name, arg.ImageUrl)
	return err
}
