// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hunting_sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHuntingSession = `-- name: DeleteHuntingSession :exec
UPDATE hunting_sessions
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type DeleteHuntingSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteHuntingSession(ctx context.Context, arg DeleteHuntingSessionParams) error {
	_, err := q.db.Exec(ctx, deleteHuntingSession, arg.ID, arg.UserID)
	return err
}

const insertHuntingSession = `-- name: InsertHuntingSession :one
INSERT INTO hunting_sessions (
    user_id, name, loadout,
    session_start, session_end, session_length_seconds,
    balance, damage, damage_per_hour, healing, healing_per_hour,
    loot, supplies, xp_gain, xp_per_hour, raw_xp_gain, raw_xp_per_hour,
    killed_monsters, looted_items, character_id
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18, $19, $20
)
RETURNING id, user_id, name, loadout, session_start, session_end, session_length_seconds, balance, damage, damage_per_hour, healing, healing_per_hour, loot, supplies, xp_gain, xp_per_hour, raw_xp_gain, raw_xp_per_hour, killed_monsters, looted_items, created_at, updated_at, deleted_at, character_id
`

type InsertHuntingSessionParams struct {
	UserID               pgtype.UUID        `json:"user_id"`
	Name                 string             `json:"name"`
	Loadout              string             `json:"loadout"`
	SessionStart         pgtype.Timestamptz `json:"session_start"`
	SessionEnd           pgtype.Timestamptz `json:"session_end"`
	SessionLengthSeconds int32              `json:"session_length_seconds"`
	Balance              int64              `json:"balance"`
	Damage               int64              `json:"damage"`
	DamagePerHour        int64              `json:"damage_per_hour"`
	Healing              int64              `json:"healing"`
	HealingPerHour       int64              `json:"healing_per_hour"`
	Loot                 int64              `json:"loot"`
	Supplies             int64              `json:"supplies"`
	XpGain               int64              `json:"xp_gain"`
	XpPerHour            int64              `json:"xp_per_hour"`
	RawXpGain            int64              `json:"raw_xp_gain"`
	RawXpPerHour         int64              `json:"raw_xp_per_hour"`
	KilledMonsters       []byte             `json:"killed_monsters"`
	LootedItems          []byte             `json:"looted_items"`
	CharacterID          pgtype.UUID        `json:"character_id"`
}

func (q *Queries) InsertHuntingSession(ctx context.Context, arg InsertHuntingSessionParams) (HuntingSession, error) {
	row := q.db.QueryRow(ctx, insertHuntingSession,
		arg.UserID,
		arg.Name,
		arg.Loadout,
		arg.SessionStart,
		arg.SessionEnd,
		arg.SessionLengthSeconds,
		arg.Balance,
		arg.Damage,
		arg.DamagePerHour,
		arg.Healing,
		arg.HealingPerHour,
		arg.Loot,
		arg.Supplies,
		arg.XpGain,
		arg.XpPerHour,
		arg.RawXpGain,
		arg.RawXpPerHour,
		arg.KilledMonsters,
		arg.LootedItems,
		arg.CharacterID,
	)
	var i HuntingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Loadout,
		&i.SessionStart,
		&i.SessionEnd,
		&i.SessionLengthSeconds,
		&i.Balance,
		&i.Damage,
		&i.DamagePerHour,
		&i.Healing,
		&i.HealingPerHour,
		&i.Loot,
		&i.Supplies,
		&i.XpGain,
		&i.XpPerHour,
		&i.RawXpGain,
		&i.RawXpPerHour,
		&i.KilledMonsters,
		&i.LootedItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CharacterID,
	)
	return i, err
}

const listHuntingSessions = `-- name: ListHuntingSessions :many
SELECT id, user_id, name, loadout, session_start, session_end, session_length_seconds, balance, damage, damage_per_hour, healing, healing_per_hour, loot, supplies, xp_gain, xp_per_hour, raw_xp_gain, raw_xp_per_hour, killed_monsters, looted_items, created_at, updated_at, deleted_at, character_id
FROM hunting_sessions
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY session_start DESC
`

func (q *Queries) ListHuntingSessions(ctx context.Context, userID pgtype.UUID) ([]HuntingSession, error) {
	rows, err := q.db.Query(ctx, listHuntingSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HuntingSession
	for rows.Next() {
		var i HuntingSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Loadout,
			&i.SessionStart,
			&i.SessionEnd,
			&i.SessionLengthSeconds,
			&i.Balance,
			&i.Damage,
			&i.DamagePerHour,
			&i.Healing,
			&i.HealingPerHour,
			&i.Loot,
			&i.Supplies,
			&i.XpGain,
			&i.XpPerHour,
			&i.RawXpGain,
			&i.RawXpPerHour,
			&i.KilledMonsters,
			&i.LootedItems,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHuntingSessionCharacter = `-- name: UpdateHuntingSessionCharacter :one
UPDATE hunting_sessions
SET character_id = $3
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, loadout, session_start, session_end, session_length_seconds, balance, damage, damage_per_hour, healing, healing_per_hour, loot, supplies, xp_gain, xp_per_hour, raw_xp_gain, raw_xp_per_hour, killed_monsters, looted_items, created_at, updated_at, deleted_at, character_id
`

type UpdateHuntingSessionCharacterParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) UpdateHuntingSessionCharacter(ctx context.Context, arg UpdateHuntingSessionCharacterParams) (HuntingSession, error) {
	row := q.db.QueryRow(ctx, updateHuntingSessionCharacter, arg.ID, arg.UserID, arg.CharacterID)
	var i HuntingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Loadout,
		&i.SessionStart,
		&i.SessionEnd,
		&i.SessionLengthSeconds,
		&i.Balance,
		&i.Damage,
		&i.DamagePerHour,
		&i.Healing,
		&i.HealingPerHour,
		&i.Loot,
		&i.Supplies,
		&i.XpGain,
		&i.XpPerHour,
		&i.RawXpGain,
		&i.RawXpPerHour,
		&i.KilledMonsters,
		&i.LootedItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CharacterID,
	)
	return i, err
}
