// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hunt_types.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHuntTypeByID = `-- name: GetHuntTypeByID :one
SELECT id, user_id, name, created_at, updated_at, deleted_at FROM hunt_types
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetHuntTypeByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetHuntTypeByID(ctx context.Context, arg GetHuntTypeByIDParams) (HuntType, error) {
	row := q.db.QueryRow(ctx, getHuntTypeByID, arg.ID, arg.UserID)
	var i HuntType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertHuntType = `-- name: InsertHuntType :one
INSERT INTO hunt_types (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at, deleted_at
`

type InsertHuntTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) InsertHuntType(ctx context.Context, arg InsertHuntTypeParams) (HuntType, error) {
	row := q.db.QueryRow(ctx, insertHuntType, arg.UserID, arg.Name)
	var i HuntType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listHuntTypesByUser = `-- name: ListHuntTypesByUser :many
SELECT id, user_id, name, created_at, updated_at, deleted_at FROM hunt_types
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListHuntTypesByUser(ctx context.Context, userID pgtype.UUID) ([]HuntType, error) {
	rows, err := q.db.Query(ctx, listHuntTypesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HuntType
	for rows.Next() {
		var i HuntType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteHuntType = `-- name: SoftDeleteHuntType :exec
UPDATE hunt_types
SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteHuntTypeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteHuntType(ctx context.Context, arg SoftDeleteHuntTypeParams) error {
	_, err := q.db.Exec(ctx, softDeleteHuntType, arg.ID, arg.UserID)
	return err
}
