// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Name              string             `json:"name"`
	World             string             `json:"world"`
	Vocation          string             `json:"vocation"`
	Level             int32              `json:"level"`
	Sex               string             `json:"sex"`
	Residence         string             `json:"residence"`
	GuildName         string             `json:"guild_name"`
	GuildRank         string             `json:"guild_rank"`
	AchievementPoints int32              `json:"achievement_points"`
	AccountStatus     string             `json:"account_status"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	IsMain            bool               `json:"is_main"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type CharacterSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	CharacterID       pgtype.UUID        `json:"character_id"`
	Level             int32              `json:"level"`
	Vocation          string             `json:"vocation"`
	World             string             `json:"world"`
	AchievementPoints int32              `json:"achievement_points"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
}

type CreatureBestiary struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Difficulty pgtype.Text        `json:"difficulty"`
	IsBoss     bool               `json:"is_boss"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type GameAssetSprite struct {
	ID         pgtype.UUID        `json:"id"`
	Kind       string             `json:"kind"`
	Name       string             `json:"name"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type HuntType struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type HuntingSession struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Name                 string             `json:"name"`
	Loadout              string             `json:"loadout"`
	SessionStart         pgtype.Timestamptz `json:"session_start"`
	SessionEnd           pgtype.Timestamptz `json:"session_end"`
	SessionLengthSeconds int32              `json:"session_length_seconds"`
	Balance              int64              `json:"balance"`
	Damage               int64              `json:"damage"`
	DamagePerHour        int64              `json:"damage_per_hour"`
	Healing              int64              `json:"healing"`
	HealingPerHour       int64              `json:"healing_per_hour"`
	Loot                 int64              `json:"loot"`
	Supplies             int64              `json:"supplies"`
	XpGain               int64              `json:"xp_gain"`
	XpPerHour            int64              `json:"xp_per_hour"`
	RawXpGain            int64              `json:"raw_xp_gain"`
	RawXpPerHour         int64              `json:"raw_xp_per_hour"`
	KilledMonsters       []byte             `json:"killed_monsters"`
	LootedItems          []byte             `json:"looted_items"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CharacterID          pgtype.UUID        `json:"character_id"`
	HuntTypeID           pgtype.UUID        `json:"hunt_type_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Role         string             `json:"role"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type WorldPlayerSnapshot struct {
	ID            pgtype.UUID        `json:"id"`
	WorldName     string             `json:"world_name"`
	Location      string             `json:"location"`
	PvpType       string             `json:"pvp_type"`
	PlayersOnline int32              `json:"players_online"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
