// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Role         string             `json:"role"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type WorldPlayerSnapshot struct {
	ID            pgtype.UUID        `json:"id"`
	WorldName     string             `json:"world_name"`
	Location      string             `json:"location"`
	PvpType       string             `json:"pvp_type"`
	PlayersOnline int32              `json:"players_online"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
