// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_player_snapshots.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSnapshotsOlderThan = `-- name: DeleteSnapshotsOlderThan :exec
DELETE FROM world_player_snapshots WHERE collected_at < $1
`

func (q *Queries) DeleteSnapshotsOlderThan(ctx context.Context, collectedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteSnapshotsOlderThan, collectedAt)
	return err
}

const getWorldAverages = `-- name: GetWorldAverages :many
SELECT world_name,
       location,
       pvp_type,
       AVG(players_online)::float8 AS avg_players_online,
       MAX(players_online)::int AS max_players_online,
       MIN(players_online)::int AS min_players_online,
       COUNT(*) AS sample_count
FROM world_player_snapshots
WHERE collected_at >= $1
  AND ($2::text = '' OR location = $2)
  AND ($3::text = '' OR pvp_type = $3)
GROUP BY world_name, location, pvp_type
ORDER BY avg_players_online DESC
`

type GetWorldAveragesParams struct {
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	Location    string             `json:"location"`
	PvpType     string             `json:"pvp_type"`
}

type GetWorldAveragesRow struct {
	WorldName        string  `json:"world_name"`
	Location         string  `json:"location"`
	PvpType          string  `json:"pvp_type"`
	AvgPlayersOnline float64 `json:"avg_players_online"`
	MaxPlayersOnline int32   `json:"max_players_online"`
	MinPlayersOnline int32   `json:"min_players_online"`
	SampleCount      int64   `json:"sample_count"`
}

func (q *Queries) GetWorldAverages(ctx context.Context, arg GetWorldAveragesParams) ([]GetWorldAveragesRow, error) {
	rows, err := q.db.Query(ctx, getWorldAverages, arg.CollectedAt, arg.Location, arg.PvpType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorldAveragesRow
	for rows.Next() {
		var i GetWorldAveragesRow
		if err := rows.Scan(
			&i.WorldName,
			&i.Location,
			&i.PvpType,
			&i.AvgPlayersOnline,
			&i.MaxPlayersOnline,
			&i.MinPlayersOnline,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldHourlyAverages = `-- name: GetWorldHourlyAverages :many
SELECT world_name,
       EXTRACT(HOUR FROM collected_at AT TIME ZONE 'UTC')::int AS hour_of_day,
       AVG(players_online)::float8 AS avg_players_online,
       COUNT(*) AS sample_count
FROM world_player_snapshots
WHERE collected_at >= $1
  AND ($2::text = '' OR world_name = $2)
  AND ($3::text = '' OR location = $3)
  AND ($4::text = '' OR pvp_type = $4)
GROUP BY world_name, hour_of_day
ORDER BY world_name, hour_of_day
`

type GetWorldHourlyAveragesParams struct {
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	WorldName   string             `json:"world_name"`
	Location    string             `json:"location"`
	PvpType     string             `json:"pvp_type"`
}

type GetWorldHourlyAveragesRow struct {
	WorldName        string  `json:"world_name"`
	HourOfDay        int32   `json:"hour_of_day"`
	AvgPlayersOnline float64 `json:"avg_players_online"`
	SampleCount      int64   `json:"sample_count"`
}

func (q *Queries) GetWorldHourlyAverages(ctx context.Context, arg GetWorldHourlyAveragesParams) ([]GetWorldHourlyAveragesRow, error) {
	rows, err := q.db.Query(ctx, getWorldHourlyAverages,
		arg.CollectedAt,
		arg.WorldName,
		arg.Location,
		arg.PvpType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorldHourlyAveragesRow
	for rows.Next() {
		var i GetWorldHourlyAveragesRow
		if err := rows.Scan(
			&i.WorldName,
			&i.HourOfDay,
			&i.AvgPlayersOnline,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldTimeSeries = `-- name: GetWorldTimeSeries :many
SELECT world_name, players_online, collected_at
FROM world_player_snapshots
WHERE collected_at >= $1
  AND ($2::text = '' OR world_name = $2)
ORDER BY collected_at ASC
`

type GetWorldTimeSeriesParams struct {
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	WorldName   string             `json:"world_name"`
}

type GetWorldTimeSeriesRow struct {
	WorldName     string             `json:"world_name"`
	PlayersOnline int32              `json:"players_online"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
}

func (q *Queries) GetWorldTimeSeries(ctx context.Context, arg GetWorldTimeSeriesParams) ([]GetWorldTimeSeriesRow, error) {
	rows, err := q.db.Query(ctx, getWorldTimeSeries, arg.CollectedAt, arg.WorldName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorldTimeSeriesRow
	for rows.Next() {
		var i GetWorldTimeSeriesRow
		if err := rows.Scan(&i.WorldName, &i.PlayersOnline, &i.CollectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWorldPlayerSnapshot = `-- name: InsertWorldPlayerSnapshot :exec
INSERT INTO world_player_snapshots (world_name, location, pvp_type, players_online, collected_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWorldPlayerSnapshotParams struct {
	WorldName     string             `json:"world_name"`
	Location      string             `json:"location"`
	PvpType       string             `json:"pvp_type"`
	PlayersOnline int32              `json:"players_online"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
}

func (q *Queries) InsertWorldPlayerSnapshot(ctx context.Context, arg InsertWorldPlayerSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertWorldPlayerSnapshot,
		arg.WorldName,
		arg.Location,
		arg.PvpType,
		arg.PlayersOnline,
		arg.CollectedAt,
	)
	return err
}
